# Config file for https://travis-ci.org/
os: linux
dist: bionic
language: php

# Define the php versions against we want to test our code
php:
- 7.2
- 7.3
- 7.4

# Note: Code coverage requires php-xDebug extension enabled on CI server

before_install:
- wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170-linux.zip
- unzip sonar-scanner-cli-4.4.0.2170-linux.zip
- mv sonar-scanner-4.4.0.2170-linux sonar

install:
- node -v
- phpenv config-rm xdebug.ini
- cp .env.travis .env
- composer self-update
- composer install --prefer-dist --optimize-autoloader --no-suggest --no-progress
- yarn install

before_script:
  - php artisan key:generate
  - mysql -e 'CREATE DATABASE travis_test DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;'
  - php artisan migrate
  - yarn production


# Testing the app (see phpunit.xml) for configs, generating Code Coverage report
script:
- phpdbg -qrr vendor/bin/phpunit

after_success:
# Submit coverage report to self-hosted SonarQube
- sonar/bin/sonar-scanner -D sonar.host.url=$SONAR_HOST -D sonar.login=$SONAR_SECRET

#after_failure:

# Monitor only these branches
branches:
  only:
  - master

# You can delete the cache using travis-ci web interface
cache:
  directories:
  - $HOME/.composer/cache

